name: interop_demo
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.3

dev_dependencies:
  ffigen: ^16.1.0
  lints: ^5.0.0
  test: ^1.24.0
